add oslc:name and dcterms:description to the ResourceShape class
eclipse/lyo pull request #204
Opened 2021-09-24 21:20 UTC by jadelkhoury

## Description

add oslc:name and dcterms:description to the ResourceShape class.
Also adding "description" to the Shape annotations in order to be able
to construct resourceshape instances from information in the
annotations.

## Checklist

- [X] This PR adds an entry to the CHANGELOG. _See https://keepachangelog.com/en/1.0.0/ for instructions. Minor edits are exempt._
- [x] This PR was tested on at least one Lyo OSLC server or adds unit/integration tests.
- [x] This PR does NOT break the API

## Issues

closes #198

2021-09-24 21:54 UTC, berezovskyi requested changes
Looks good, thank you! Could you please add a line to the changelog?

2021-09-25 05:04 UTC, jadelkhoury commented
I did. But hopefully in the right place?
![image](https://user-images.githubusercontent.com/7108694/134759032-918b12d2-2c40-4e3b-9ded-fbeb883c6b7c.png)

2021-09-25 05:09 UTC, merged

2021-09-25 09:42 UTC, berezovskyi commented
Ah, you did that on master.

2021-09-26 11:42 UTC, jadelkhoury commented
that is right. i didn't think about it.