Functionality to reset the token cache.
eclipse/lyo pull request #422
Opened 2023-10-25 07:16 UTC by Jad-el-khoury

Functionality to allow the application to reset the token cache if it identifies that the token is no longer valid.

## Checklist

- [x] This PR adds an entry to the CHANGELOG. _See https://keepachangelog.com/en/1.0.0/ for instructions. Minor edits are exempt._
- [x] This PR was tested on at least one Lyo OSLC server (e.g. manual workflow on [Lyo Sample](https://github.com/OSLC/lyo-samples/actions/workflows/maven-smoke-manual.yml) and [OSLC RefImpl](https://github.com/oslc-op/refimpl/actions/workflows/maven-acceptance-manual.yml)) or adds unit/integration tests.
- [x] This PR does NOT break the API

2023-10-26 06:02 UTC, Jad-el-khoury commented
@berezovskyi ! The removal s done from the application, so it is not part of this library. Similar to the calls removeConnector() & removeCredentials() to remove the Connector and Credentials from the session. 

And, this is not really a Cache. In that there is no other copies any other place. It's a necessary mapping table from the Connector objects to the oauth tokens saved on the server side.

2023-10-26 10:15 UTC, berezovskyi commented
Right, that's why I didn't see the usage.

2023-10-26 11:49 UTC, Jad-el-khoury commented
> Right, that's why I didn't see the usage.

and your verdict is ... ?

2023-10-26 16:29 UTC, berezovskyi requested changes
Would have been good to have a test or a demo in refimpl. But I think we can make an exception given that this PR doesn't touch the existing functionality and is relatively hard to test due to Server+session presence. We can merge without further tests.

But please:

- **Fix tabs/spacing!**
- **Install the Editorconfig plugin:** https://editorconfig.org/#download You choose if you want it in VS Code, Eclipse, or Notepad++. IntelliJ has it out of the box. This will make sure you will not have such problems again.

2023-10-26 16:31 UTC, berezovskyi commented
<img width="980" alt="image" src="https://github.com/eclipse/lyo/assets/64734/d8293c07-b6a5-4362-a69a-0bcd44f50fcc">

tabs and spaces 😭 

https://github.com/eclipse/lyo/blob/master/.editorconfig#L10

2023-10-27 09:15 UTC, Jad-el-khoury commented
thanks @berezovskyi ! tabs updated. will merge now.

2023-10-27 09:15 UTC, merged

2023-10-27 18:30 UTC, berezovskyi commented
@Jad-el-khoury I don't think you installed the plugin 🕵️‍♂️  The trailing newline is missing, it seems?

2023-10-28 11:32 UTC, Jad-el-khoury commented
@berezovskyi I fixed the tabs/spaces manually. so no, did not install the plugin. But will look into it in future use. Thanks.