adding java folder to be able to create source jar files.
eclipse/lyo pull request #604
Opened 2024-09-04 08:40 UTC by Jad-el-khoury

## Description

adding src/java folders to the "net.oauth.core-oauth-****-jakarta" projects in order to  create source jar files, which are necessary to publish on Maven Central.

Note that the jar file will contain the added readme file.
<img width="446" alt="image" src="https://github.com/user-attachments/assets/67dff04a-ab09-4b1c-9456-519ea6f4df76">

2024-09-04 08:41 UTC, Jad-el-khoury commented
@berezovskyi!

These changes are made after I tagged the Beta release. Do we need to start all over again or is it ok?

2024-09-04 10:15 UTC, berezovskyi commented
It needs to be beta2. Otherwise the deploy will fail, Eclipse Maven enforces one deploy per version. That's why I always revert to SNAPSHOT immediately after every release, even milestone releases.

2024-09-04 10:17 UTC, berezovskyi requested changes
Non-snapshot versions must differ for every commit.

2024-09-17 19:21 UTC, berezovskyi approved these changes

2024-09-17 19:21 UTC, merged